### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by royabaaff** [NidukaAkalanka/x-ui-english#92]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

hello sir , and thanks for your great work
i faced an issue and searched anywhere  but didn't get any solution and I'm newb and i think i done something wrong so,  sorry 
 evey time after adding my client i get this error database is locked
as it says "invalid inbounds err " removed my inbounds, add new remark , new config and even i fressh start several times my ubunto 20.04 and again agter adding first client and testing connection error appears  and in the end errors make service stops and not working

### Version of x-ui

<details>

```console
$ x-ui version

x-ui-english 0.2.1.2

XRAY Configuration Template

{
  "log": {
    "loglevel": "info", 
    "access": "./access.log"
  },
 
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}



### x-ui log or xray log

<details>

```console
# paste log here
```
Jan 01 01:18:23 freedom x-ui[68204]: 2023/01/01 01:18:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:22:53 freedom x-ui[68204]: 2023/01/01 01:22:53 WARNING - disable invalid Client err: database is locked
Jan 01 01:22:58 freedom x-ui[68204]: 2023/01/01 01:22:58 WARNING - disable invalid inbounds err: database is locked
Jan 01 01:23:23 freedom x-ui[68204]: 2023/01/01 01:23:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:23:28 freedom x-ui[68204]: 2023/01/01 01:23:28 WARNING - disable invalid inbounds err: database is locked
Jan 01 01:31:23 freedom x-ui[68204]: 2023/01/01 01:31:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:31:53 freedom x-ui[68204]: 2023/01/01 01:31:53 WARNING - disable invalid Client err: database is locked
Jan 01 01:32:29 freedom x-ui[68204]: 2023/01/01 01:32:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:32:29 freedom x-ui[68204]: 2023/01/01 01:32:28 WARNING - disable invalid inbounds err: database is locked
Jan 01 01:32:53 freedom x-ui[68204]: 2023/01/01 01:32:53 WARNING - disable invalid Client err: database is locked
Jan 01 01:34:23 freedom x-ui[68204]: 2023/01/01 01:34:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:34:55 freedom x-ui[68204]: 2023/01/01 01:34:55 WARNING - disable invalid Client err: database is locked
Jan 01 01:43:23 freedom x-ui[68204]: 2023/01/01 01:43:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:44:53 freedom x-ui[68204]: 2023/01/01 01:44:53 WARNING - disable invalid Client err: database is locked
Jan 01 01:44:58 freedom x-ui[68204]: 2023/01/01 01:44:58 WARNING - disable invalid inbounds err: database is locked
Jan 01 01:49:23 freedom x-ui[68204]: 2023/01/01 01:49:23 WARNING - disable invalid Client err: database is locked
Jan 01 01:49:31 freedom x-ui[68204]: 2023/01/01 01:49:28 WARNING - disable invalid inbounds err: database is locked
Jan 01 01:49:53 freedom x-ui[68204]: 2023/01/01 01:49:53 WARNING - disable invalid Client err: database is locked
Jan 01 01:49:58 freedom x-ui[68204]: 2023/01/01 01:49:58 WARNING - disable invalid inbounds err: database is locked
Jan 01 08:33:23 freedom x-ui[68204]: 2023/01/01 08:33:23 WARNING - disable invalid Client err: database is locked
Jan 01 08:33:28 freedom x-ui[68204]: 2023/01/01 08:33:28 WARNING - disable invalid inbounds err: database is locked
Jan 01 08:44:53 freedom x-ui[68204]: 2023/01/01 08:44:53 WARNING - disable invalid Client err: database is locked
Jan 01 08:50:53 freedom x-ui[68204]: 2023/01/01 08:50:53 WARNING - disable invalid Client err: database is locked
Jan 01 08:50:58 freedom x-ui[68204]: 2023/01/01 08:50:58 WARNING - disable invalid inbounds err: database is locked
Jan 01 08:55:23 freedom x-ui[68204]: 2023/01/01 08:55:23 WARNING - disable invalid Client err: database is locked
Jan 01 08:57:23 freedom x-ui[68204]: 2023/01/01 08:57:23 WARNING - disable invalid Client err: database is locked
Jan 01 09:03:53 freedom x-ui[68204]: 2023/01/01 09:03:53 WARNING - disable invalid Client err: database is locked
Jan 01 09:05:53 freedom x-ui[68204]: 2023/01/01 09:05:53 WARNING - disable invalid Client err: database is locked
Jan 01 09:08:23 freedom x-ui[68204]: 2023/01/01 09:08:23 WARNING - disable invalid Client err: database is locked
Jan 01 09:11:23 freedom x-ui[68204]: 2023/01/01 09:11:23 WARNING - disable invalid Client err: database is locked
Jan 01 09:27:23 freedom x-ui[68204]: 2023/01/01 09:27:23 WARNING - disable invalid Client err: database is locked
Jan 01 09:28:53 freedom x-ui[68204]: 2023/01/01 09:28:53 WARNING - disable invalid Client err: database is locked
Jan 01 09:28:58 freedom x-ui[68204]: 2023/01/01 09:28:58 WARNING - disable invalid inbounds err: database is locked
Jan 01 09:35:23 freedom x-ui[68204]: 2023/01/01 09:35:23 WARNING - disable invalid Client err: database is locked

</details>

**Comment by NidukaAkalanka** [comment]
Hi there @royabaaff !

Upon getting x ui menu by running `sudo x-ui` , you'll see an option to uninstall x ui. Proceed to that and after that, try installing again with the single command. 

Don't know why you have titled this as database locked. If you have seen that somewhere, try running `sudo chown root /etc/x-ui-english/x-ui-english.db` from the root + root user.

Please comment down if the problem exists even after. Providing the x-ui logo would help a lot though. It can be extracted by running `sudo systemctl status x-ui`

**Comment by royabaaff** [comment]
thanks for quick response , sorry for mising logs i attached the logs but apparently somehow its been missing so i will put it again .
done uninstalling with  `x-ui uninstall`  and install again , then `x-ui restart`  and run `sudo chown root /etc/x-ui-english/x-ui-english.db` with root user and again `x-ui restart` and reboot the vps , but still same thing happens .
as i said i test it sevaral times with fresh ubunto 20.04 and add just one user for test but every time i get the same error 

![1](https://user-images.githubusercontent.com/83171039/210174124-ca5a9337-aae5-4389-9a62-aac96f87c9a0.png)

**Comment by hatinati2** [comment]
plz update fork
now xray 1.7.2.2
but is yours is 1.6.4

**Comment by royabaaff** [comment]
> plz update fork now xray 1.7.2.2 but is yours is 1.6.4

thanks for response  i will do that

**Comment by aliafshany** [comment]
@royabaaff 
did you get manage to solve this issue?
i get this error too.

with fresh OS reinstallation i get again.
still don't know the cause of that.
hope the developer (@NidukaAkalanka )  would investigate this.

**Comment by royabaaff** [comment]
not even close to any answer , as i said even  test it on a clean ubunto and just created 1 user  but a second after start , those errors showed up

**Comment by aliafshany** [comment]
unfortunately although my naming i used random creator button but still I get this error.
i really don't know the cause of that
please do help.

**Comment by pouyasalimi** [comment]
I have 2 VPSs, and both of them have the same and latest version of [x-ui-english](https://github.com/NidukaAkalanka/x-ui-english) One of them has the same issue. I have just one user and connection on it.

`Aug 02 17:25:32  x-ui[436763]: 2023/08/02 17:25:32 WARNING - disable invalid Client err: database is locked

Aug 02 17:30:47  x-ui[436763]: 2023/08/02 17:30:47 WARNING - add traffic failed: database is locked; no valid 
transaction

Aug 02 17:45:47  x-ui[436763]: 2023/08/02 17:45:47 WARNING - add traffic failed: database is locked; no valid 
transaction

Aug 02 18:15:02  x-ui[436763]: 2023/08/02 18:15:02 WARNING - disable invalid Client err: database is locked

Aug 02 18:17:07  x-ui[436763]: 2023/08/02 18:17:07 WARNING - add traffic failed: database is locked; no valid 
transaction
`

**Comment by Zickam** [comment]
Same issue here. Updating the x-ui didn't help. I have like 4 servers based on 3X-UI and only one of them encountered this issue. I have set up some simple security for all of them: default ssh port changed, panel has long secret path, password and login were changed so they are pretty long too

**Comment by aliafshany** [comment]
> Rebooting VPS helped me with this issue
> 
> `reboot now`

😐😐😐
Do you really think that nobody has ever tried that except you? What a genius

**Comment by VyacheslavKokorin** [comment]
> ```
> # apt install sqlite3
> # systemctl stop x-ui.service
> # sqlite3 /etc/x-ui/x-ui.db <<SQL
> PRAGMA journal_mode = WAL;
> PRAGMA busy_timeout = 5000;
> VACUUM;
> SQL
> # systemctl start x-ui.service
> ```
> 
> Works for me

Thanks bro! It worked for me too.

**Comment by Kuchizu** [comment]
> ```
> # apt install sqlite3
> # systemctl stop x-ui.service
> # sqlite3 /etc/x-ui/x-ui.db <<SQL
> PRAGMA journal_mode = WAL;
> PRAGMA busy_timeout = 5000;
> VACUUM;
> SQL
> # systemctl start x-ui.service
> ```
> 
> Works for me

Thank you bro! Also worked for me.
